[features]
seeds = false
[programs.localnet]
p_to_p_chat = "8rgXH6wodLMnkcDMkdpVLMTbnDQUjDaHgAAhw7BuysQE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/abstracted/solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
